version: 2
registries:
  github-gems:
    type: rubygems-server
    url: https://rubygems.pkg.github.com/sevgibson
    token: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}
updates:
  - package-ecosystem: bundler
    directory: "/"
    registries:
      - github-gems
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/"
    registries:
      - github-npm
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
